# Generated by Django 5.0.3 on 2026-07-28 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion_corta', models.CharField(max_length=200)),
                ('historia', models.TextField(help_text='Storytelling del fundador/local')),
                ('direccion', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('rango_precio', models.CharField(choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$')], default='$', max_length=3)),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('dias_operacion', models.CharField(help_text='Ej: Lun-Sáb', max_length=100)),
                ('es_camaleonico', models.BooleanField(default=False, help_text='¿Cambia de gema/mood según la hora?')),
                ('es_socio_fundador', models.BooleanField(default=False)),
                ('es_ficticio', models.BooleanField(default=True, help_text='Marca si es un local de demo, no un negocio real')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('gema_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locales_principales', to='locales.tipogema')),
                ('gema_secundaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locales_secundarios', to='locales.tipogema')),
                ('moods', models.ManyToManyField(related_name='locales', to='locales.mood')),
            ],
        ),
        migrations.CreateModel(
            name='FotoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='locales/')),
                ('es_portada', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='locales.local')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
