# Generated by Django 5.0.3 on 2026-08-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0002_local_fotolocal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
