# Generated by Django 5.0.3 on 2026-08-15 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0003_mood_slug'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GemaColeccionada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateTimeField(auto_now_add=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.local')),
                ('tipo_gema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locales.tipogema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_obtenida'],
                'unique_together': {('usuario', 'local')},
            },
        ),
    ]
