# Generated by Django 5.0.3 on 2026-08-21 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0003_mood_slug'),
        ('usuarios', '0002_gemacoleccionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='referido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_referidos', to='locales.local'),
        ),
    ]
