# Generated by Django 5.0.3 on 2026-08-21 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfilusuario_referido_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('icono', models.CharField(default='award', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InsigniaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateTimeField(auto_now_add=True)),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.insignia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_obtenida'],
                'unique_together': {('usuario', 'insignia')},
            },
        ),
    ]
