# Generated by Django 5.0.3 on 2026-08-18 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locales', '0003_mood_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaFidelidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitas_requeridas', models.PositiveSmallIntegerField(default=5)),
                ('recompensa_descripcion', models.CharField(help_text='Ej: Bebida gratis, 15% de descuento', max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('local', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta_fidelidad', to='locales.local')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoFidelidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitas_acumuladas', models.PositiveSmallIntegerField(default=0)),
                ('recompensas_canjeadas', models.PositiveSmallIntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_fidelidad', to=settings.AUTH_USER_MODEL)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='fidelidad.tarjetafidelidad')),
            ],
            options={
                'unique_together': {('usuario', 'tarjeta')},
            },
        ),
    ]
